#! /bin/false

# Copyright (C) 2018 Guido Flohr <guido.flohr@cantanea.com>,
# all rights reserved.

# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What the Fuck You Want
# to Public License, Version 2, as published by Sam Hocevar. See
# http://www.wtfpl.net/ for more details.

package Parse::Kalex::Generator;

use strict;

use Locale::TextDomain qw(kayak);

sub new {
    my ($class, $lexer) = @_;

    bless {
        __errors => 0,
        __top_code => [],
        __def_code => [],
        __lexer => $lexer,
        __filename => '',
        __start_conditions => {
            INITIAL => 1,
        },
        __xstart_condtions => {}
    }, $class;
}

sub addTopCode {
    my ($self, $code) = @_;

    my @location = $self->{__lexer}->yylocation;
    push @{$self->{__top_code}}, [ $code, @location ];

    return $self;
}

sub addDefCode {
    my ($self, $code) = @_;

    my @location = $self->{__lexer}->yylocation;
    push @{$self->{__def_code}}, [ $code, @location ];

    return $self;
}

sub setUserCode {
    my ($self, $code) = @_;

    my @location = $self->{__lexer}->yylocation;
    $self->{__user_code} = [$code, @location ];

    return $self;
}

sub checkStartCondition {
    my ($self, $condition) = @_;

    if (!exists $self->{__start_conditions}->{$condition}
        && !exists $self->{__xstart_conditions}->{$condition}) {
        my $location = $self->{__lexer}->yylocation;
        warn __x("{location}: undeclared start condition '{condition}'.\n",
                 location => $location, condition => $condition);
        ++$self->{__errors};
    }

    return $self;
}

sub addRule {
    my ($self, $start_conditions, $regex, $code) = @_;

    return $self;
}

sub errors {
    my ($self) = @_;

    return if !$self->{__errors};

    return $self->{__errors};
}

sub generate {
    my ($self, %options) = @_;

    # FIXME! Merge in options from scanner definition.

    my $output = '';
    my $top_code = $self->__topCode;

    if (defined $options{package}) {
        $output .= <<EOF;
#! /bin/false

# A lexical scanner generated by kalex.

${top_code}package $options{package};

EOF
    } else {
        $output .= <<EOF;
#! /usr/bin/env perl

# A lexical scanner generated by kalex.

${top_code}
EOF

        $output .= $self->__readModuleCode('Parse/Kalex/Snippets/main.pm');

        $output .= "package Parse::Kalex::Lexer;\n";
    }

    $output .= $self->__defCode;

    $output .= $self->__readModuleCode('Parse/Kalex/Snippets/Base.pm');

    if (!defined $options{package}) {
        $output .= "package main;\n\nno strict;\n\n";
    }

    $output .= $self->__userCode;

    return $output;
}

sub __topCode {
    my ($self) = @_;

    my $output = '';

    foreach (@{$self->{__top_code}}) {
        my ($snippet, @location) = @$_;

        chomp $snippet;
        $snippet .= "\n";
        $output .= $self->__addLocation($snippet, @location);
        $output .= $snippet;
    }

    return $output;
}

sub __defCode {
    my ($self) = @_;

    my $output = '';

    foreach (@{$self->{__def_code}}) {
        my ($snippet, @location) = @$_;

        chomp $snippet;
        $snippet .= "\n";
        $output .= $self->__addLocation($snippet, @location);
        $output .= $snippet;
    }

    return $output;
}

sub __userCode {
    my ($self) = @_;

    return '' if !defined $self->{__user_code};

    my ($snippet, @location) = @{$self->{__user_code}};
    chomp $snippet;
    $snippet .= "\n";

    my $output = $self->__addLocation($snippet, @location);
    $output .= $snippet;

    return $output;
}

sub __addLocation {
    my ($self, $snippet, $filename, $lineno) = @_;

    my $location = '';
    if ($filename ne $self->{__filename} || $lineno != $self->{__lineno}) {
        $location = qq{#line $lineno "$filename"\n};
    } 
    $self->{__filename} = $filename;
    $self->{__lineno} = $lineno + ($snippet =~ y/\n/\n/);

    return $location;
}

sub __readModuleCode {
    my ($self, $module) = @_;

    my $code = '';
    eval {
        my $filename;
        foreach my $path (@INC) {
            $filename = File::Spec->catfile($path, $module);
            last if -e $filename;
        }
        die __x("cannot locate '{module}' in \@INC.  (\@INC contains: {INC}).",
                module => $module, INC => join ' ', @INC)
            if !-e $filename;

        open my $fh, '<', $filename
            or die __x("error opening '{filename}' for"
                       . " reading: {error}!",
                       filename => $filename, error => $!);
        while (defined(my $line = $fh->getline)) {
            last if $line =~ /^package/;
        }
        while (defined(my $line = $fh->getline)) {
            last if $line =~ /^1;/;
            $code .= $line;
        }

        if (!length $code) {
            die __x("could not find any code in module '{module}''",
                    module => $module);
        }
    };
    if ($@) {
        die __x("error reading code from mode '{module}': {err}",
                module => $module, err => $@);
    }

    return $code;
}

1;
